### ISSUE TITLE
Generics and namespaces

### ISSUE THREAD

**Issue by thekid** [xp-framework/core#144]
```php
use lang\Object;

#[generic(self= 'T')]
class Test extends Object {

}
```

This does not work as expected - the name `Object` gets resolved to the current namespace instead of the `use` statement being honored - /cc @pdietz

**Comment by thekid** [comment]
> This does not work as expected 

As far as I see, and as far as the test suite now verifies, this statement is not true. Must've been another problem, possibly a typo?

**Comment by pdietz** [comment]
Hmm, good it works.

Might be it is related to XP v5.11.0 I am using and didn't mention before...
I rule out a typo, since the class definition (without generics) is working when using it with EASC.

Since it is working with the latest version and there is a workaround in my scenario, by using the namespaces directly with the classes, digging deeper probably isn't worth the effort.

Thank you for looking into it nonetheless and verifying it's working :)

**Comment by thekid** [comment]
> related to XP v5.11.0 

Wow, that's not even the newest XP5-SERIES release :stuck_out_tongue: 

XP 5 has been in maintenance mode since XP 6.0.0 was released in February 2015 - we generally only backport fixes one release back, so wouldn't touch XP5 nowadays.

> Thank you for looking into it nonetheless 

Sure, you're welcome!
